from typing import Any, Callable

from cairocffi.surfaces import ImageSurface

class ImageLoadingError(ValueError): ...

class Pixbuf:
    def __init__(self, pointer: Any) -> None: ...
    def __getattr__(self, name: str) -> Callable[..., Any]: ...

def decode_to_image_surface(
    image_data: bytes, width: int | None = ..., height: int | None = ...
) -> tuple[ImageSurface, str]: ...
